#!/usr/bin/env sh
. "${0%/*}/h"


# Rodar o phpstan

./vendor/bin/phpstan

if [ $? -ne 0 ]; then
    echo "Opa!! Deu ruima aqui com o PHPSTAN. Arrume antes de continuar... "

    exit 1;
fi;

# Formatar cada arquivo alterado

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

for FILE in STAGED_FILES

do

    ./vendor/bin/pint "${FILE}"

    git add "${FILE}"

done;
